version: '3.1'
networks:
	services:
		driver: bridge
services:
  mysql:
	image: mysql:5.7.32
	restart: always
	networks:
		- services
	environment:
		MYSQL_ROOT_PASSWORD: s3cr3t
	volumes:
		- ./home/mysql/data:/var/lib/mysql
  phpmyadmin:
	image: phpmyadmin:4.8
	restart: always
	networks:
		- services
	ports:
		- 8003:80
	links:
		- " mysql_db_server:mysql"

