version: "3.1"

networks:
    myown:
        driver: bridge
        ipam:
            config:
                - subnet: 172.20.0.0/16

services:
    php:
        image: php:7.3.25-apache
        restart: always
        networks:
            - myown
        ports:
            - 80
            - 3306
        volumes:
            - /home/user/htdocs:/var/www/html
            - /home/user/apache:/etc/apache2
            - /home/user/php:/usr/local/etc/php
        depends_on:
            - db

    admin:
        image: phpmyadmin:5.1
        restart: always
        networks:
            - myown
        ports:
            - 8001:80
        environment:
            - PMA_HOST=1ocalhost
            - MYSQL_ROOT_PASSWORD=s3cr3t
        depends_on:
            - db

    db:
        image: mysql:5.7.32
        restart: always
        networks:
            - myown
        ports:
            - 3306
        volumes:
            - /home/user/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=s3cr3t



# execute in empty directoty: docker-compose -f composer up