package org.europa.together.chapter04;

public class SystemUnderTest {

    private int parameter;

    public int power() {
        return calculate(parameter, parameter);
    }

    public void setParameter(int parameter) {
        this.parameter = parameter;
    }

    public int getParameter() {
        return this.parameter;
    }

    private int calculate(int operand01, int operand02) {
        return operand01 * operand02;
    }

    // NetBeans autogenerated for BeanMatcherTest
    @Override
    public String toString() {
        return "SystemUnderTest{" + "parameter=" + parameter + '}';
    }

    @Override
    public int hashCode() {
        int hash = 7;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final SystemUnderTest other = (SystemUnderTest) obj;
        if (this.parameter != other.parameter) {
            return false;
        }
        return true;
    }
}
